/*
 * Auth.
 */

// Login.
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REFRESH_PENDING = 'REFRESH_PENDING';

// Logout.
export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

/*
 * Profile.
 */
// Fetch all.
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING';
export const FETCH_PROFILE_REJECTED = 'FETCH_PROFILE_REJECTED';
export const FETCH_PROFILE_FULFILLED = 'FETCH_PROFILE_FULFILLED';

/*
 * Achievements.
 */
// Fetch all.
export const FETCH_ACHIEVEMENTS = 'FETCH_ACHIEVEMENTS';
export const FETCH_ACHIEVEMENTS_PENDING = 'FETCH_ACHIEVEMENTS_PENDING';
export const FETCH_ACHIEVEMENTS_REJECTED = 'FETCH_ACHIEVEMENTS_REJECTED';
export const FETCH_ACHIEVEMENTS_FULFILLED = 'FETCH_ACHIEVEMENTS_FULFILLED';

/*
 * Projects.
 */
// Fetch all.
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_PENDING = 'FETCH_PROJECTS_PENDING';
export const FETCH_PROJECTS_REJECTED = 'FETCH_PROJECTS_REJECTED';
export const FETCH_PROJECTS_FULFILLED = 'FETCH_PROJECTS_FULFILLED';